# Generated by Django 4.0.6 on 2023-03-23 05:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderData', models.TextField()),
                ('orderAmount', models.FloatField()),
                ('orderStatus', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Duplicate', 'Duplicate')], default='Pending', max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('price', models.TextField()),
                ('halfprice', models.TextField()),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.category')),
            ],
        ),
        migrations.CreateModel(
            name='ratingdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('reservationId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('noOfPeople', models.IntegerField()),
                ('date', models.DateField()),
                ('timeSlot', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('tableNumber', models.CharField(default='Not Assigned', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('orderDataId', models.AutoField(primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=100)),
                ('customerName', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('address', models.TextField(null=True)),
                ('orderData', models.TextField()),
                ('orderType', models.CharField(choices=[('TakeAway', 'TakeAway'), ('Dining', 'Dining')], max_length=100)),
                ('payment', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Cheque', 'Cheque')], max_length=100)),
                ('otherCost', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
                ('cgst', models.CharField(max_length=100)),
                ('sgst', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=100)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 3, 23, 10, 31, 41, 740059))),
            ],
        ),
        migrations.CreateModel(
            name='TakeAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('orderType', models.CharField(default='TakeAway', max_length=100)),
                ('address', models.TextField()),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCart',
            fields=[
                ('product_list', models.TextField()),
                ('cart_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='productDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productFeature', models.TextField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.product')),
            ],
        ),
        migrations.CreateModel(
            name='customerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('HOME', 'HOME'), ('OFFICE', 'OFFICE'), ('HOTEL', 'HOTEL'), ('OTHER', 'OTHER')], default='HOME', max_length=10)),
                ('address_nickname', models.CharField(default='', max_length=100, null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookATable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tableNumber', models.IntegerField()),
                ('orderType', models.CharField(default='Dining', max_length=100)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
            ],
        ),
    ]
